### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by maarten-ic** [multiscale/muscle3#173]
Add integration with docker, such that `muscle_manager` can directly launch components in a docker container.

Example:

```yaml
implementations:
  component_in_docker:
    image: my_own_docker_image
    executable: /path/in/docker/image/to/my/executable
```

Main benefit compared specifying `docker` as executable and providing the correct arguments:

- `muscle_manager` can arrange Docker port forwarding, such that this component can talk to the `muscle_manager` and peer instances.
- `muscle_manager` can transparently set the correct environment variables that are required for the program running inside Docker
