### ISSUE TITLE
Document debugging tricks: run gdb in xterm or screen

### ISSUE THREAD

**Issue by maarten-ic** [multiscale/muscle3#189]
When you have access to a graphical environment, a nice debugging trick is to do:

```
implementations:
  <component>:
    executable: xterm
    args:
    - -e
    - 'gdb --args <executable> <args...>'
```

This opens a new `xterm` and starts the GNU debugger pointing to your actually executable.

On non-GUI environments a similar thing can be achieved with GNU screen:

```
implementations:
  <component>:
    executable: screen
    args:
    - -dmS
    - gdb_session
    - gdb
    - --args
    - <executable>
    - <arg1>
    - <arg2...>
```

Which starts a detached `screen` session called `gdb_session`. You can attach to this session when executing (in a separate command line):
```
screen -r gdb_session
```

Note: this should not be a detailed explanation on how to use `gdb` and/or `screen`: there's plenty of information on either on the internet.

**Comment by maarten-ic** [comment]
Note: instead of xterm, you can also use other terminals (that probably look better). For example, gnome-terminal:

```yaml
implementations:
  <component>:
        executable: /usr/bin/gnome-terminal
        args:
        - --tab
        - --active
        - --title="MUSCLE3 wrapper"
        - -- /usr/bin/gdb --args <executabe> <args...>
```
