### ISSUE TITLE
Adding an option to the YMMSL file to activate a python environment

### ISSUE THREAD

**Issue by DavidPCoster** [multiscale/muscle3#248]
Just as it is possible to require modules that need to be loaded by, for example:

```
implementations:
  on_hpc:
    modules: c++ openmpi
    executable: /home/user/models/mpi_model
    execution_model: openmpi

```
would it be possible to supply a command to activate a python environment?  Or to provide the path to such an environment?
