### ISSUE TITLE
Add receive_all()/receive_any() for vector ports

### ISSUE THREAD

**Issue by LourensVeen** [multiscale/muscle3#79]
We need this for better load balancing, and eventually for resizable vector ports.

**Comment by LourensVeen** [comment]
There may be cases where we have multiple `S` ports, and want to receive_any() across all of them. So we should consider having an ability to listen across an arbitrary set of ports rather than only on all slots on a single port.

**Comment by maarten-ic** [comment]
Some bullet points from a discussion with @LourensVeen and myself around timelines and vector ports:

- Vector ports are used to communicate with ensembles (N micro instances, each connected to a single slot) which are not resizable, and to a vector port of another component (which is resizable).
  - Wishlist feature: allow resizing ensemble ports (which would instantiate additional instances)
- To correctly support resizable vector ports with timelines, we will now require that each slot of a O_I/S vector port is sent/received on exactly once, before we can send O_F messages, or do another O_I/S loop.
- For load balancing scenarios it could be useful to allow sending on only part of the slots of O_I ports (and receiving on just those corresponding S ports). Some options to consider to make this work:
  - Use vector timelines, such that each slot of a vector port becomes an independent timeline. Example:
    ```yaml
    components:
    - load_balancer:
        ports:
          f_init: front_in
          o_f: back_out
          timeline ensemble[]:
            o_i: back_out
            s: back_in
    ```
  - Send special "skip" messages for each slot that wasn't sent on, such that a component on the other end knows that no message will arrive.
